library(readxl)
library(plyr)
library(dplyr)
library(tidyverse)
library(magrittr)

print("Renewable Generation")

Renewable_Generation <- read_excel("Data Sources/Regional Generation/Regional Generation.xlsx", 
                                   sheet = "Generation and supply", col_names = FALSE)

Renewable_Generation  <- as.data.frame(t(Renewable_Generation))
Renewable_Generation  <- Renewable_Generation [c(5:23)]

names(Renewable_Generation ) <- c("Country", 
              "Electricity generated by major power producers",
              "Electricity generated by other generators",
              "Total generated",
              "Own use by Other generators",
              "Electricity supplied (net) by Other generators",
              "Used in pumping at pumped storage and other own use by MPPs",
              "Electricity supplied (net) by MPPs",
              "Electricity transferred to England (net of receipts)",
              "Electricity transferred to Northern Ireland (net of receipts)",
              "Electricity transferred to Europe (net of receipts)",
              "Transfers from other generators to public supply",
              "Transmission losses",
              "Distribution losses and theft",
              "Consumption from public supply",
              "Consumption by autogenerators",
              "Total electricity consumption",
              "Electricity sales (public supply)",
              "Statistical difference"
              )

Renewable_Generation$Year <- substr(Renewable_Generation$Country, 1, 4)
Renewable_Generation$Country <- substr(Renewable_Generation$Country,6,str_length(Renewable_Generation$Country))

Renewable_Generation<- Renewable_Generation[c(20,1:19)]

Renewable_Generation$Country <- as.character(Renewable_Generation$Country)

Renewable_Generation[c(1,3:20)] %<>% lapply(function(x) as.numeric(as.character(x)))

Renewable_Generation <- as.data.frame(Renewable_Generation)

Renewable_Generation <- Renewable_Generation[complete.cases(Renewable_Generation),]

write.csv(Renewable_Generation,
            "Output/Renewable Generation/GenSupplyReadable.csv",
            row.names = FALSE)

